### PR TITLE
Correct splted tooltip position on init

### LINKED ISSUE #418: Spit Tooltip. Bad positioning when init.
In first init right tooltip in horisontal range slider positioned bottom. But when i click - it positioned well.

### PR DESCRIPTION
**Pull request by krzysiek1507**
Fixes #418 
http://plnkr.co/edit/Nyw1kViPSrMO5OcVZB24?p=preview
cc @seiyria please merge quickly and release if good ;)

### CODE REVIEW

**Comment by seiyria** [comment]
We'll need a unit test for this to verify this behavior doesn't occur in future builds. After that, it's probably good (assuming it passes our CI).

**Comment by krzysiek1507** [comment]
@seiyria now ok?

**Comment by seiyria** [comment]
This looks good to me. @rovolution, am I missing anything here or is it good to merge?

**Comment by rovolution** [comment]
@seiyria just checked it on my localhost and it looks good. Thanks for the PR and for actually following our guidelines @krzysiek1507!

Ill merge and patch bump

**Comment by krzysiek1507** [comment]
@seiyria @rovolution thanks!

**Pull request merged**
