### PR TITLE
Change tracks components from "left/right" to "low/high"

### PR DESCRIPTION
**Pull request by mgwalker**
As requested by @rovolution in #297.  Changed track segment names from left/right to low/high throughout.  Hopefully covered everything.

### CODE REVIEW

**Comment by rovolution** [comment]
@mgwalker thank you for doing that! just need to rename the spec file and ill merge it in

**Comment by mgwalker** [comment]
Whoops.  Renaming that file didn't even occur to me.  There you go!

**Comment by rovolution** [comment]
@mgwalker the segments dont appear to be highlighted:

mgwalker
image

**Comment by mgwalker** [comment]
Whoops.  Yep, you're right.  I completely forgot to change the inlined styles in the index.tpl.  I've pulled all your changes from today and merged my stuff back into it, including the index.tpl fix.

**Comment by rovolution** [comment]
@mgwalker looks good. merging in!

**Pull request merged**
