### PR TITLE
Babel + other housekeeping

### PR DESCRIPTION
**Pull request by rovolution**
@seiyria Decided to do a little housekeeping. Went ahead and added the following:

- Moving all src to `/src` directory
- Transpiling JS with Babel
- Adding 'Other Guidelines' section to CONTRIBUTING.MD
- Updating README with Grunt CLI tasks
- Update postpublish script to reference transpiled code
- Freezing dependency versions (this allows us to ensure the module and grunt tasks always have consistent/repeatable behavior)
- Adding an `.nvmrc` file for Node 5.x.x. This version of node comes with NPM 3.x.x, which creates a flat dependency tree for `node_modules`, which basically eliminates the need for bower as our client-side deps management solution

Look over the changes and let me know what you think! After the @zsiswick PR gets merged in, I want to add those changes to this branch, merge, and do a major version bump.

Will also add a CHANGELOG once the next PR gets merged in

### CODE REVIEW

**Comment by seiyria** [comment]
This looks nice, but I don't see any changes made to move to ES6, it just adds Babel... am I missing something?

**Comment by rovolution** [comment]
> This looks nice, but I don't see any changes made to move to ES6, it just adds Babel... am I missing something?

that is correct. Want to just hook Babel into our build process as step 1. After that, we can begin refactoring/rewriting to ES6

**Comment by rovolution** [comment]
@seiyria Just merged in the PR from @zsiswick and rebased against `master`...if everything looks good I will try to merge these changes in later this week

**Comment by seiyria** [comment]
Sounds good to me!

**Comment by rovolution** [comment]
merging!

**Pull request merged**
