### PR TITLE
Removed opacity and changed colour of handles.

### PR DESCRIPTION
**Pull request by liddellj**
More closely follows the style of Bootstrap 3 (no opacity, uses same
colour of blue as btn-primary).

### CODE REVIEW

**Comment by seiyria** [comment]
Seems fine to me. @rovolution?

**Comment by rovolution** [comment]
@liddellj could you update the .sass file as well?

https://github.com/seiyria/bootstrap-slider/blob/master/sass/slider.scss

**Comment by liddellj** [comment]
Done (although I'd feel more comfortable if someone could double check the SASS file for me).

**Comment by rovolution** [comment]
merged in. thanks for your contribution!

**Pull request merged**
