### PR TITLE
Fix sass mixin usage

### PR DESCRIPTION
**Pull request by armpogart**
Minor fix for sass, the mixin was used incorrectly.

### CODE REVIEW

**Comment by seiyria** [comment]
Looks simple enough for me.

**Comment by armpogart** [comment]
Another fix for the linter (mixins should come before declaration) to pass CI build.

**Comment by rovolution** [comment]
merged and released to v9.9.1. thanks again for your contribution @armpogart!

**Comment by armpogart** [comment]
np, I'm glad I could fix even such a small bug on the plugin that I use almost on all my projects. Thanks for your great product!

**Pull request merged**
