### PR TITLE
Fix Tooltip #232

### PR DESCRIPTION
**Pull request by Dennis14e**

### CODE REVIEW

**Comment by seiyria** [comment]
Please provide a jsfiddle so we can verify this fix.

**Comment by Dennis14e** [comment]
Without fix: http://jsfiddle.net/Dennis14e/z4saj0L4/
Fix: http://jsfiddle.net/Dennis14e/rj41c4co/

**Comment by seiyria** [comment]
Seems fine to me. @rovolution?

**Comment by rovolution** [comment]
I would like to see an automated test that fails in the broken version/passes in the working version

**Comment by Dennis14e** [comment]
I don't know how to do it.
I've just taken the fix from the Issue - and it works.

**Comment by rovolution** [comment]
> I don't know how to do it.

Please look at our existing test suite as guidance. Automated tests are crucial as they allows us to ensure regressions do not occur in the future

**Comment by Dennis14e** [comment]
I've tried it, but i don't get it - I still don't know how this should work.
You can see the bug in the old version very clearly - and in my version it works.

**Comment by rovolution** [comment]
included as part of @Bhoft's PR: https://github.com/seiyria/bootstrap-slider/commit/90e89c93679affd2d8b7ca2afaa0eb9bd53fead4

**Pull request closed without merging**
