### PR TITLE
Fix offset calculation when contained in relatively positioned parent. Fixes #340

### LINKED ISSUE #340: Using bootstrap-slider as dropdown menu[bug]
Everything is ok, except using it as a dropdown menu.When I move the slider after dropdown, it is not the exact position where I press.
http://stackoverflow.com/questions/29142031/using-bootstrap-slider-as-dropdown-menu

### PR DESCRIPTION
**Pull request by bcroesch**
Apologize if all my pushes were spamming anyone. Kept trying to get the damn white space to line up (looked fine in my editor).

### CODE REVIEW

**Comment by seiyria** [comment]
Nope, no one got spammed by this. Thanks. Can we see this in action via a jsfiddle or some equivalent?

**Comment by bcroesch** [comment]
Original fiddle from the issue (shows working & broken versions): http://jsfiddle.net/KyleMit/dy0qobyp/4/

Fiddle with fix (both working): http://jsfiddle.net/gd92637g/1/

**Comment by rovolution** [comment]
how does this look inside of a modal? we had people complain about the slider when it was contained within a modal

could you add that to your PR?

**Comment by bcroesch** [comment]
Here you go: http://jsfiddle.net/gd92637g/2/

**Comment by seiyria** [comment]
Seems like it works to me. Thanks!

**Pull request merged**
