### PR TITLE
Bug-fix: set this.eventToCallbackMap property values to undefined instead of null on destroy()

### PR DESCRIPTION
**Pull request by rovolution**
Fixes https://github.com/seiyria/bootstrap-slider/issues/640

### CODE REVIEW

**Comment by seiyria** [comment]
Looks good to me. Maybe a semantics thing, but would it make more sense to `delete` it instead of waiting for it to get gc'd?

**Comment by rovolution** [comment]
`delete` just removes the reference and marks it for GC on the subsequent GC pass. Won't make much of a difference other than removing the eventName key from the `this. eventToCallbackMap` object

**Comment by rovolution** [comment]
@seiyria went ahead and refactored to use `delete`

**Comment by rovolution** [comment]
@snurby7 merged and published to 9.4.0! thanks again!

**Pull request merged**
