### PR TITLE
Add insertBefore bool option

### PR DESCRIPTION
**Pull request by moshfeu**
Now, the user can choose if the slider will create before or after the input and hide or not the original element. It's good if you want to show  the element and show the slider as popup.

Demo: https://jsfiddle.net/4hj4Lq0w/3/

### CODE REVIEW

**Comment by seiyria** [comment]
I have literally never seen this use case before, and I'm not sure it's valuable. It seems more confusing than anything.

**Comment by moshfeu** [comment]
That's why I attached a demo =)

**Comment by seiyria** [comment]
Right, I saw the demo and it still took a while. I am personally not seeing the use case still, but that aside; for us to accept this, we would prefer if you added tests, an example, and documentation since this is a brand new feature.

**Comment by rovolution** [comment]
yea i am little confused by this use case (and I do not think it is general enough to adapt to a broader range of cases). Going to close this PR for now

**Pull request closed without merging**
