### PR TITLE
Created a Code Climate config

### PR DESCRIPTION
**Pull request by larkinscott**
Pull Requests
=============
Please accompany all pull requests with the following (where appropriate):

- I started on a Code Climate config with ESLint, CSSLint and our duplication engine enabled. 
- It's currently using an inferred config for ESLint, but we can customize this to fit your project's needs.
- Our duplication engine is set to a slightly elevated mass_threshold. This can be fine-tuned as well!

- [ ] unit tests (we use [Jasmine 1.3](http://jasmine.github.io/1.3/introduction.html))
- [ ] JSFiddle (or an equivalent such as CodePen, Plunker, etc) or screenshot/GIF with new feature or bug-fix
- [ ] Link to original Github issue (if this is a bug-fix)
- [ ] documentation updates to README file
- [ ] examples within [/tpl/index.tpl](https://github.com/seiyria/bootstrap-slider/blob/master/tpl/index.tpl) (for new options being added)
- [ ] Passes CI-server checks (runs automated tests, JS source-code linting, etc..). To run these on your local machine, type `grunt test` in your Terminal within the bootstrap-slider repository directory

### CODE REVIEW

**Comment by rovolution** [comment]
@larkinscott looks good. Is there a CodeClimate badge or something of the sort we can embed into our README?

**Comment by rovolution** [comment]
btw @seiyria forwarded me your email last night so I am aware of this

**Comment by seiyria** [comment]
@rovolution there is! https://codeclimate.com/github/seiyria/bootstrap-slider/badges

**Comment by larkinscott** [comment]
Hi @rovolution! Thanks for taking a look! I can add our badge to your README and send over a PR (you should see it shortly).

**Comment by rovolution** [comment]
that would be awesome @larkinscott! I'll go ahead and merge this one for now

**Pull request merged**
