### PR TITLE
Fixed getting options with complicated names from data attributes

### PR DESCRIPTION
**Pull request by kirilvit**
Changed underscores with dashes for correct getting data attributes values

### CODE REVIEW

**Comment by seiyria** [comment]
Seems simple enough. Do we need tests for this kind of behavior @rovolution?

**Comment by rovolution** [comment]
@seiyria I would not think so (I think the current tests we have in the DataAttributesSpec file should cover this), but it would be nice to find out which specific data attribute was the cause of this change, and at least add a test for that to the DataAttributesSpec file. Which data attribute caused you to make this change @kirilvit?

**Comment by kirilvit** [comment]
@rovolution it was `ticks_labels`. If you try to set it via data attribute, it would not work.

Actually, it could be any attribute with underscore in name.

**Comment by rovolution** [comment]
@kirilvit cool. yea if you could add a test to the [ElementDataAttributesSpec](https://github.com/seiyria/bootstrap-slider/blob/master/test/specs/ElementDataAttributesSpec.js) file for the ```tick_labels``` attribute, that would be perfect.

**Comment by kirilvit** [comment]
Ok,I'll do it tomorrow

**Comment by rovolution** [comment]
@kirilvit awesome thanks!

**Comment by kirilvit** [comment]
How do you run tests? I'm new to Jasmine, and when I run Grunt to build SpecRunner.html from tpl it throws an error  
`Running "jasmine:src" (jasmine) task
Warning: Error while processing "tpl/SpecRunner.tpl" file. Used --force, continuing.`

**Comment by rovolution** [comment]
should be just ```grunt test```

**Comment by kirilvit** [comment]
Thanks. I used a different version of Jasmine, and that's why it was failing.

**Comment by kirilvit** [comment]
I've just committed a test for this fix. And also I've updated examples page, replaced `data-slider-ticks-labels="['$0', '$100', '$200', '$300', '$400']"` with `data-slider-ticks-labels='["$0", "$100", "$200", "$300", "$400"]'`, because JSON.parse needs correct JSON.

**Comment by rovolution** [comment]
This looks good...merging in. Thanks for the PR @kirilvit!

**Pull request merged**
