### PR TITLE
(feat) Add logarithmic scale

### PR DESCRIPTION
**Pull request by MelleB**
This commit allows the scale to be changed from `linear` to
`logarithmic` using the newly introduced `scale` option.

### CODE REVIEW

**Comment by MelleB** [comment]
I'll post a JSFiddle in a minute

**Comment by seiyria** [comment]
Don't forget the tests!

**Comment by MelleB** [comment]
Minimal test and an example are in there. Not sure how to go about keyboard navigation in relation to the logarithmic values. Do we want to keep using step here?

**Comment by seiyria** [comment]
I'm actually not sure what would be most natural, to be honest.

**Comment by MelleB** [comment]
JSFiddle: http://jsfiddle.net/v8htqnfz/

**Comment by MelleB** [comment]
Rebased branch

**Comment by rovolution** [comment]
@MelleB looks like the keyboard functionality is broken on the logarithmic slider

**Comment by MelleB** [comment]
@seiyria  @rovolution Yes, I didn't touch any of the keyboard stuff yet. I'm not sure how keyboard navigation on a logarithmic slider should look like. Would we just use the default (linear) step here?

AFAICT using step size results in extremely long key-presses. Using the logarithmic increments on the other hand results in loss of precision. (And how would you configure the step option if we do use logarithmic increments?)

Would love some input on this.

**Comment by seiyria** [comment]
Honestly I'm quite unsure about this. I think it should probably use step size, and if someone has problems, they can slide it another way. I was hoping to see what [this library](http://refreshless.com/nouislider/slider-values/) does, but it seems like they don't even have keyboard support.

**Comment by rovolution** [comment]
I would go ahead and use step size, despite the fact it may lead to long key presses. If people leave feedback we can always incorporate it later

**Comment by rovolution** [comment]
@MelleB The keyboard functionality for the range slider appears to be broken.

Its throwing the following error:

```
Uncaught TypeError: Cannot read property 'toFixed' of undefined
```

Could you fix that? Im looking through our KeyboardSupportSpec and am somewhat confused how our tests are not breaking on that

**Comment by MelleB** [comment]
Didn't see that error, weird. What browser are you using?

Sent from mobile
Op 14 feb. 2015 19:04 schreef "Rohit Kalkur" <notifications@github.com>:

**Comment by MelleB** [comment]
Looking into it...

**Comment by MelleB** [comment]
This fixes the issue.

**Comment by rovolution** [comment]
@MelleB merged! Thanks again for this awesome PR

**Pull request merged**
