### PR TITLE
Fixes Issue #884: Hovering over ticks displays the tick index

### LINKED ISSUE #884: Hovering over ticks displays the tick index
I also noticed this while working on Issue #882 

I should also add that the tooltip does not move over the tick, it stays in the same place.

https://github.com/seiyria/bootstrap-slider/blob/59745c648eb9a4e937783c7177521219212112ab/src/js/bootstrap-slider.js#L1176-L1177

https://github.com/seiyria/bootstrap-slider/blob/59745c648eb9a4e937783c7177521219212112ab/src/js/bootstrap-slider.js#L1172-L1184

You can follow the steps below, and you'll notice the value of tooltip is the index of the tick.

1. Open a console
2. Move the handle to the middle (value of `5`).
3. Hover over the rightmost tick once. Should display `hover: 5`
4. Repeat step 3 multiple times. Should display `hover: 2`

Note: Also try hovering over the leftmost tick.

`console.log('hover:', mySlider.getValue());`

https://jsfiddle.net/xq0cgoa5/

Issues
=============
**NOTE:** Before filing a new issue, please search through the open issues list and check to see if an existing issue already exists that describes your problem. If so, leave a comment within that issue with the checklist items described below.

Please make sure you include the following in your issue report where appropriate:

- [x] JSFiddle (or an equivalent such as CodePen, Plunker, etc) with the an example demonstrating the bug
- [x] Instructions to replicate the bug in the Fiddle

### PR DESCRIPTION
**Pull request by jespirit**
Fixes #884 

This displays the correct value for the tick and correctly positions the tooltip above the tick.

Will add unit tests.

Pull Requests
=============
Please accompany all pull requests with the following (where appropriate):

- [x] unit tests (we use [Jasmine 2.x.x](https://jasmine.github.io/2.2/introduction))
- [x] Link to original Github issue (if this is a bug-fix)
- [ ] Passes CI-server checks (runs automated tests, JS source-code linting, etc..). To run these on your local machine, type `grunt test` in your Terminal within the bootstrap-slider repository directory

### CODE REVIEW

**Comment by jespirit** [comment]
Added some unit test coverage that **codeclimate** wouldn't be too happy about it.

My unit tests before fix:

issue-884-unit-tests

**Comment by jespirit** [comment]
I added more unit tests for displaying tooltips for a vertical slider.

My unit tests before fix:

issue-884-unit-tests-vertical

**Codeclimate** would be really unhappy. I essentially copied the same code for the horizontal slider except I changed the `offsetLeft` to be `offsetTop`.

**Comment by jespirit** [comment]
I copied and pasted more unit tests. You can check the commits.

I don't think I can refactor that stuff. I could try? It was hard to manage. One mistake and I had to change other parts of the code =(

**Comment by jespirit** [comment]
~~As per your request/challenge~~ I refactored the code.

I tried to use as many variables as I can and moved as much initialization code inside `beforeEach()` functions.

In fact, I just copied all the tooltip unit tests and changed a few variables to test against the RTL slider.

Before my fix:

issue-884-all-unit-tests

Good luck, trying to maintain that code!

**Comment by rovolution** [comment]
LGTM 👍

**Comment by jespirit** [comment]
I refactored the unit tests so it's easier to manage.

**Pull request merged**
