### PR TITLE
Fixes #381 in original slider

### LINKED ISSUE #381: Wrong slider position recognition with position:absolute
Hi Guys.. When positioning the slider or one of its containers with ***position:absolute;*** css and maybe moving them with ex. ***left:50%;*** or something, (in my case I was using the slider in an off canvas sidebar that moved with css) the slider position inside its inner functions is not recognised correctly, with the result of it not working properly.

I discovered that this happens due to line 1414 where this function is used to track the offset of the slider, by browsing its offset parents and getting their offset left property. This is the code:

	_offsetLeft: function(obj){
		var offsetLeft = obj.offsetLeft;
		while((obj = obj.offsetParent) && !isNaN(obj.offsetLeft)){
			offsetLeft += obj.offsetLeft;
		}
		return offsetLeft;
	}},

for me a simple line fix worked, where replacing this function with the new one that simply returns directly the position of the slider in relation to the screen so it can be compared with touch position and compute distanceToSlide properly... fixed code:

	_offsetLeft: function(obj){
		return obj.getBoundingClientRect().left;
	}

Thanks!

### PR DESCRIPTION
**Pull request by mitsos1os**
Check issue #381

### CODE REVIEW

**Comment by seiyria** [comment]
Looks fine. I don't know how testable this is but I think it's a good change overall!

**Comment by rovolution** [comment]
@mitsos1os could you rebase this against master?

Also, could you create a JS fiddle for this? I'd like to see how the slider operates inside of a modal, if possible. Thanks!

**Comment by seiyria** [comment]
Sorry, but this no longer builds against our latest changes. We'd also like to see it in action!

**Comment by mitsos1os** [comment]
Hi, I am sorry i was really busy these days, I will do what you asked as soon as I get the chance!

**Comment by mitsos1os** [comment]
Also checkout the JSfiddle you requested with modal operation...
http://jsfiddle.net/1Lyb36ty/3/

**Comment by rovolution** [comment]
@mitsos1os could you rebase against the current `master` branch? thanks! promise i wont ask you to rebase again :)

**Comment by mitsos1os** [comment]
@rovolution Just did!

**Comment by seiyria** [comment]
Should this get merged then before something happens again, @rovolution? :P

**Comment by rovolution** [comment]
@seiyria yea ill merge this in soon when i get a chance

**Pull request merged**
