### PR TITLE
Respect the scale factor of container

### PR DESCRIPTION
**Pull request by utilmind**
This is the fix for issue described several years ago in https://github.com/seiyria/bootstrap-slider/issues/625

To reproduce this issue, just scale the container of the Bootstrap Slider with CSS, set `transform: scale(N)`, where N is different than 1 (increase or decrease size of the container and its entire content).

Also updated `_toPercentage()` method now has some size & speed optimizations.

### CODE REVIEW

**Comment by ae-gladkikh** [comment]
When will this correction be adopted?

**Comment by seiyria** [comment]
@ae-gladkikh I unfortunately do not have time to maintain this project. If you or anyone you know would like to maintain the package, I would be happy to add you/them as a maintainer!

**Comment by utilmind** [comment]
> If you or anyone you know would like to maintain the package, I would be happy to add you/them as a maintainer!

@seiyria, Add me as maintainer. I don't have time too, but I can do a code review and approve good improvements. Still better than nothing!

**Comment by utilmind** [comment]
@seiyria Actually I just saw invitation. Thanks for inviting! Accepted.

**Comment by seiyria** [comment]
You're welcome @utilmind - thank you for offering to help out! We really appreciate it!

**Comment by utilmind** [comment]
Figuring out failed tests, reading rules...

Anyway going to approve this improvement. It was successfully used in multiple projects during last 2 years.
Just couple of demos (both have no issues with scale factor on page):
  1. https://utilmind.com/demos/2022/emotion-picker/
  2. https://pro-pursuit.com/

**Comment by utilmind** [comment]
Sorry, I still can't figure out how to pass the tests or how to modify them with my existing privileges. (Or maybe I need access to Netlify, but I don't really want it...)

Although I have successfully built the package on my local environment with some changes (I stopped using Grunt and Jasmine). Probably the only option to me is to maintain the fork in the future, although it will be w/o tests anyway...

P.S. I'm going to try to merge PR despite the failed tests...

**Comment by utilmind** [comment]
Ok, was able to pass checks after upgrading NPM version, but build preview seems not good... Digging further...

**Comment by utilmind** [comment]
Yay!

**Comment by utilmind** [comment]
> When will this correction be adopted?

Done. Please test it and let me know if you will have any issues.
(This is my first merge here, so despite I hope that everything will be fine, issues are possible.)

**Comment by utilmind** [comment]
For some reason "dist" folder doesn't contain updated packages. I thought that Netlify supposed to build it automatically... :-/
I'll figure this out and update files in "dist" ASAP.

**Comment by ae-gladkikh** [comment]
> > When will this correction be adopted?
> 
> @ae-gladkikh Done. Please test it and let me know if you will have any issues. (This is my first merge here, so despite I hope that everything will be fine, issues are possible.)

Good news, i will test ASAP

**Comment by utilmind** [comment]
@ae-gladkikh now really released, files in "dist" folder updated.

(It turns out that it's not fully automated, the script that prepares the release should be run manually. Anyway, it's ready now.)

**Pull request merged**
