### PR TITLE
Fix for issue #364

### PR DESCRIPTION
**Pull request by thomato**
Truncate percentage for comparison based on percentage to be compared

### CODE REVIEW

**Comment by seiyria** [comment]
Hm, this seems ok I think. @rovolution? Maybe a test would be nice but I'm not sure here.

**Comment by rovolution** [comment]
I would like a test of some sort...if anything to validate the slider value

**Comment by thomato** [comment]
Got it. Working on that. Thanks for the feedback.

**Comment by thomato** [comment]
Added test for handle swapping. Would appreciate any feedback.

**Comment by seiyria** [comment]
It seems fine, although I'm not sure you needed to bump it. We have a grunt task for that.

**Comment by thomato** [comment]
I think the bump was from the merge, didn't bump for my changes.

**Comment by seiyria** [comment]
Then sure, it looks fine to me. @rovolution?

**Comment by rovolution** [comment]
is there anyway we could write the tests to call either the `setValue` method or simulate a `mousemove` event like [this test](https://github.com/seiyria/bootstrap-slider/blob/master/test/specs/ConflictingOptionsSpec.js#L16-L31)?

I would rather we simulate the value change that way, since that is our "public" interface, and if the value is what we expect from using our public method, then we can assume the private method is implemented properly.

**Comment by thomato** [comment]
@rovolution Thanks for the tip. Updated the tests to use mouse events instead.

**Comment by thomato** [comment]
hello, just wanted to inform that the test is ready, not sure if anyone had the chance to look at this yet.

**Comment by seiyria** [comment]
Not yet. To be honest, it looks ok to me but I'm not used to tests that use the mouse yet.

**Comment by thomato** [comment]
OK, no worries, just checking.

**Comment by rovolution** [comment]
@thomato sorry for the delay! I am on vacation right now and will merge/bump the version when I get back

**Comment by thomato** [comment]
No problem, thank you.

**Comment by thomato** [comment]
Thanks for the merge!

**Comment by rovolution** [comment]
thank you for the contribution!

**Pull request merged**
