### PR TITLE
Added getElement() method.

### PR DESCRIPTION
**Pull request by ttsda**

### CODE REVIEW

**Comment by seiyria** [comment]
I think this is simple enough to not need tests; it's just a getter. I'll merge this.

**Comment by ttsda** [comment]
:)

**Comment by rovolution** [comment]
@seiyria remember to update the version and publish!

```bash
grunt bump:minor
npm publish
```

**Comment by seiyria** [comment]
Ah yeah, I forget. I usually just do stuff from the web interface :P I'll bump it now.

**Comment by seiyria** [comment]
Also, @rovolution - I can't publish to npm. Only you have access to do that.

**Comment by rovolution** [comment]
@seiyria I went ahead and published. Also added you as a collaborator to the NPM module, so you should be able to `npm publish` in the future

**Pull request merged**
