### PR TITLE
Add jquery dependency

### PR DESCRIPTION
**Pull request by Laboratory**
Hello,

I added jquery dependency for building through webpack.

Thx, Vitaly

### CODE REVIEW

**Comment by seiyria** [comment]
jQuery is not a dependency of this application. If you want to use it, that is on you, not us.

**Comment by Laboratory** [comment]
In ur code
`````javascript
if(typeof define === "function" && define.amd) {
    define(["jquery"], factory);
}
`````

When build through webpack I see error
`````javascript
ERROR in ./~/bootstrap-slider/js/bootstrap-slider.js
Module not found: Error: Cannot resolve module 'jquery' in /Users/Laboratory/projects/***/node_modules/bootstrap-slider/js
 @ ./~/bootstrap-slider/js/bootstrap-slider.js 36:2-29
`````

**Comment by seiyria** [comment]
In that case, I would rather have a patch that makes that code work as expected. Neither of us have used webpack before (AFAIK), so that's unfamiliar territory to us.

**Comment by DomKM** [comment]
I'm running into this issue as well.

**Pull request closed without merging**
